
package com.leeves.wsjwsrnewdemo.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "LeevesServiceImplService", targetNamespace = "http://webservice.wsjwsnewdemo.leeves.com/", wsdlLocation = "http://172.16.11.32:7000/jws/leevesService?wsdl")
public class LeevesServiceImplService
    extends Service
{

    private final static URL LEEVESSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException LEEVESSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName LEEVESSERVICEIMPLSERVICE_QNAME = new QName("http://webservice.wsjwsnewdemo.leeves.com/", "LeevesServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://172.16.11.32:7000/jws/leevesService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LEEVESSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        LEEVESSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public LeevesServiceImplService() {
        super(__getWsdlLocation(), LEEVESSERVICEIMPLSERVICE_QNAME);
    }

    public LeevesServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), LEEVESSERVICEIMPLSERVICE_QNAME, features);
    }

    public LeevesServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, LEEVESSERVICEIMPLSERVICE_QNAME);
    }

    public LeevesServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LEEVESSERVICEIMPLSERVICE_QNAME, features);
    }

    public LeevesServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LeevesServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns LeevesService
     */
    @WebEndpoint(name = "LeevesServiceImplPort")
    public LeevesService getLeevesServiceImplPort() {
        return super.getPort(new QName("http://webservice.wsjwsnewdemo.leeves.com/", "LeevesServiceImplPort"), LeevesService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LeevesService
     */
    @WebEndpoint(name = "LeevesServiceImplPort")
    public LeevesService getLeevesServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.wsjwsnewdemo.leeves.com/", "LeevesServiceImplPort"), LeevesService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LEEVESSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw LEEVESSERVICEIMPLSERVICE_EXCEPTION;
        }
        return LEEVESSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
